### PR TITLE
Changing intercept point for gin, make sure interfaces could be group…

### PR DESCRIPTION
**Pull request by dylanforest**
Changing intercept point for gin, make sure interfaces could be grouped when params defined in relativePath.

### CODE REVIEW

**Comment by dylanforest** [comment]
Is this CI failure  a problem? I think it's not code's fault.

**Review by mrproliu — APPROVED** [review]

**Comment by wu-sheng** [comment]
> Is this CI failure a problem? I think it's not code's fault.

I rerun the CIs.

**Comment by dylanforest** [comment]
> > Is this CI failure a problem? I think it's not code's fault.
> 
> I rerun the CIs.
Looks like it fails again

**Comment by mrproliu** [comment]
It looks like GitHub Action caused the failure, we can only run a few more times to try. :(

**Comment by dylanforest** [comment]
Sad...

**Comment by wu-sheng** [comment]
@mrproliu Is there some env changed?

**Comment by dylanforest** [comment]
Same problems everytime, maybe some settings wrong？

**Comment by dylanforest** [comment]
Any news?

**Comment by wu-sheng** [comment]
> Any news?

We had fixed this, and now this is able to merge.

**Pull request merged**
