### PR TITLE
fix: when not route is found, the gin operation name is "http.Method:", example: "GET:".

### PR DESCRIPTION
**Pull request by Hair1ossTeenager**
fix: when not route is found, the gin operation name is "http.Method:", example: "GET:".

### CODE REVIEW

**Comment by wu-sheng** [comment]
What is URL path? If domain(ip) included?

**Comment by wu-sheng** [comment]
@mrproliu do we use e2e tool here? If so, we need a fix.

**Comment by mrproliu** [comment]
> @mrproliu do we use e2e tool here? If so, we need a fix.

Nope, we haven't used the e2e tool here. Just using mock OAP server for plugin testing.

**Comment by mrproliu** [comment]
@Hair1ossTeenager Could you help to add some example code to the plugin test?

**Comment by Hair1ossTeenager** [comment]
> What is URL path? If domain(ip) included?

View source code:
```go
// FullPath returns a matched route full path. For not found routes
// returns an empty string.
//
//	router.GET("/user/:id", func(c *gin.Context) {
//	    c.FullPath() == "/user/:id" // true
//	})
func (c *Context) FullPath() string {
	return c.fullPath
}
```

**Comment by Hair1ossTeenager** [comment]
> @Hair1ossTeenager Could you help to add some example code to the plugin test? Also, the [CHANGES.md](https://github.com/apache/skywalking-go/blob/main/CHANGES.md) should be updated.

Done.

**Review by mrproliu — DISMISSED** [review]
Cool!

**Comment by wu-sheng** [comment]
CI Fails, need some fix.

**Comment by mrproliu** [comment]
It looks like it's the docker-compose issue, I will create another PR to fix it.

**Review by mrproliu — APPROVED** [review]

**Pull request merged**
