### PR TITLE
fix special case for ParseVendorModule

### PR DESCRIPTION
**Pull request by vearne**
fix [#11718](https://github.com/apache/skywalking/issues/11718)

### CODE REVIEW

**Comment by mrproliu** [comment]
Please update the [CHANGES.md](https://github.com/apache/skywalking-go/blob/main/CHANGES.md)

**Comment by vearne** [comment]
> Please update the [CHANGES.md](https://github.com/apache/skywalking-go/blob/main/CHANGES.md)

ok

**Review by mrproliu — APPROVED** [review]

**Comment by wu-sheng** [comment]
CI fails. Is there anything wrong?

**Comment by vearne** [comment]
> CI fails. Is there anything wrong?

I've fixed it

**Review by wu-sheng — APPROVED** [review]

**Pull request merged**
