### PR TITLE
[Test] Update the supported versions for fiber

### PR DESCRIPTION
**Pull request by CodePrometheus**
Update the supported versions for fiber.

### CODE REVIEW

**Comment by wu-sheng** [comment]
49.0 is not supposed?

**Comment by CodePrometheus** [comment]
I suspect that this https://github.com/golang/go/issues/62409 may be causing the error in the pulsar CI test.

**Comment by CodePrometheus** [comment]
It seems that the env may be unstable, could we discuss it in Slack?

**Comment by wu-sheng** [comment]
Yes, slack is open for discussion. @mrproliu may be back tomorrow or today night.

**Comment by CodePrometheus** [comment]
Just to locate the problem, I close it, thx.

**Pull request closed without merging**
